name: 'sitetracker_source'
version: '1.0.0'
config-version: 2
require-dbt-version: ">=0.18.0"

vars:
  sitetracker_source:
    calendar_event_assignment: "{{ source('sitetracker','sitetracker_calendar_event_assignment_c') }}"
    calendar_event: "{{ source('sitetracker','sitetracker_calendar_event_c') }}"
    contact: "{{ source('sitetracker','contact') }}"
    job: "{{ source('sitetracker','sitetracker_job_c') }}"
    site: "{{ source('sitetracker','sitetracker_site_c') }}"
    timesheet_user: "{{ source('sitetracker','sitetracker_timesheet_user_c') }}"
    user: "{{ source('sitetracker','user') }}"

  contacts_pass_through_columns: []
  jobs_pass_through_columns: []
  sites_pass_through_columns: []
